const {
  generateOtpController,
  verifyOtpController,
  dropdwonCodeController,
  registerController,
  loginController,
  viewRolesController,
  addPermToRoleController,
  viewPermissionsController,
  removePermFromRoleController,
  getUserByTokenController,
  addRoleController,
  changeRoleStatusController,
  editRoleController,
  deleteRoleController,
  viewUsersController,
  createUserController,
  editUserController,
  deleteUserController,
  changeUserStatusController,
} = require("./Admin");
const {
  addStateController,
  viewStatesController,
  editStateController,
  deleteStateController,
  addDistrictController,
  editDistrictController,
  viewDistrictController,
  deleteDistrictController,
} = require("./State");

module.exports = {
  generateOtpController,
  verifyOtpController,
  dropdwonCodeController,
  registerController,
  loginController,
  viewRolesController,
  addPermToRoleController,
  viewPermissionsController,
  removePermFromRoleController,
  getUserByTokenController,
  addRoleController,
  changeRoleStatusController,
  editRoleController,
  deleteRoleController,
  viewUsersController,
  createUserController,
  editUserController,
  deleteUserController,
  changeUserStatusController,
  addStateController,
  viewStatesController,
  editStateController,
  deleteStateController,
  addDistrictController,
  editDistrictController,
  viewDistrictController,
  deleteDistrictController,
};
