module.exports = {
  ACTIVE: "Active",
  PENDING: "Pending",
  INACTIVE: "Inactive",
  LOCKED: "Locked",
  SALT_ROUNDS: 10,
  ALREADY_EXISTS: "Email id/phone already exists.",
  ALREADY_EXISTS_MAPPING: "Mapping already exists",
  INVALID_CREDENTIALS: "Invalid credentials",
  DUPLICATE: "Already exists",
  OTP_SENT: "OTP sent successfully",
  OTP_EXPIRE: 10,
  USER_NOT_FOUND: "User not found",
  NOT_FOUND: "Not found",
  OTP_VERIFIED: "OTP verified successfully",
  INVALID_OTP: "Invalid OTP",
  APPLICANT: "APP",
  OTP_REGISTRATION_SUBJECT: "OTP for verification",
  SUCCESS: "success",
  FORGOT_PASSWORD: "Forgot Password",
  UPDATE_NUMBER: "Update Number",
  PASSWORD_CHANGED: "Password changed successfully",
  PHONE: "phone",
  SERVER_ERROR_MESSAGE: "Internal Server Error",
  MAX_OTP_COUNT_TIME: 10,
  RESEND_OTP_COUNT: 3,
  MESSAGE_TEMPLATE_TYPES: {
    REGISTRATION_OTP: "REGISTRATION_OTP",
    LOGIN: "LOGIN",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  },
  RESOURCES: {
    TEMP: "TEMP_RESOURCE",
  },
  PERMS: {
    ADD: "ADD",
    EDIT: "EDIT",
    VIEW: "VIEW",
    DELETE: "DELETE",
    EXPORT: "EXPORT",
    PROCESS: "PROCESS",
  },
};
