const {
  addRole,
  generateOtp,
  verifyOtp,
  dropdownCode,
  register,
  login,
  viewRoles,
  addPermToRole,
  viewPermissions,
  removePermFromRole,
  getUserByToken,
  changeRoleStatus,
  editRole,
  deleteRole,
  viewUsers,
  createUser,
  editUser,
  deleteUser,
  changeUserStatus,
} = require("./Admin");
const {
  addState,
  viewStates,
  editState,
  deleteState,
  addDistrict,
  editDistrict,
  viewDistrict,
  deleteDistrict,
} = require("./State");

module.exports = {
  addRole,
  generateOtp,
  verifyOtp,
  dropdownCode,
  register,
  login,
  viewRoles,
  addPermToRole,
  viewPermissions,
  removePermFromRole,
  getUserByToken,
  changeRoleStatus,
  editRole,
  deleteRole,
  viewUsers,
  createUser,
  editUser,
  deleteUser,
  changeUserStatus,
  addState,
  viewStates,
  editState,
  deleteState,
  addDistrict,
  editDistrict,
  viewDistrict,
  deleteDistrict,
};
