const {
  addRole,

  dropdownCode,
  register,
  login,
  viewRoles,
  addPermToRole,
  viewPermissions,
  removePermFromRole,
  getUserByToken,
  changeRoleStatus,
  editRole,
  deleteRole,
  viewUsers,
  createUser,
  editUser,
  deleteUser,
  changeUserStatus,
} = require("./Admin");
const { dropdown } = require("./dropdown");
const { generateOtp, verifyOtp } = require("./otp");
const {
  sellerProfile,
  addEmployee,
  addProduct,
  sellerViewProducts,
  sellerViewProductById,
  sellerViewEmployees,
  sellerEditEmployee,
  sellerViewEmployeeById,
  sellerDeleteEmployee,
  sellerEditProduct,
  sellerDeleteProduct,
  sellerViewProfile,
  sellerEditProfile,
} = require("./Seller");
const {
  addState,
  viewStates,
  editState,
  deleteState,
  addDistrict,
  editDistrict,
  viewDistrict,
  deleteDistrict,
} = require("./State");

module.exports = {
  dropdown,
  addRole,
  generateOtp,
  verifyOtp,
  dropdownCode,
  register,
  login,
  viewRoles,
  addPermToRole,
  viewPermissions,
  removePermFromRole,
  getUserByToken,
  changeRoleStatus,
  editRole,
  deleteRole,
  viewUsers,
  createUser,
  editUser,
  deleteUser,
  changeUserStatus,
  addState,
  viewStates,
  editState,
  deleteState,
  addDistrict,
  editDistrict,
  viewDistrict,
  deleteDistrict,
  sellerProfile,
  addEmployee,
  addProduct,
  sellerViewProducts,
  sellerViewProductById,
  sellerEditProduct,
  sellerDeleteProduct,
  sellerViewEmployees,
  sellerViewEmployeeById,
  sellerEditEmployee,
  sellerDeleteEmployee,
  sellerViewProfile,
  sellerEditProfile,
};
